service: admin
package:
  individually: false

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: api.indywise.com
    staging: staging-api.indywise.com
    dev: dev-api.indywise.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    certificateName: '*.indywise.com'
    stage: ${self:custom.stage}
    # Set the basePath to whatever you would like it to, by default it will be
    # same as the `service` name.
    basePath: ${self:service}
    createRoute53Record: true
  tableName:
    admin: ${self:custom.stage}-${self:service}-admin
    attractions: ${self:custom.stage}-${self:service}-attractions

  dynamodb:
    stages:
      - dev
    start:
      port: 8888
      inMemory: true
      migrate: true
    migration:
      dir: offline
  serverless-offline:
    httpPort: 7000

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName.table}'
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName.accounts}/index/email-index'
  environment:
    TABLE_NAME_ADMIN: ${self:custom.tableName.admin}
    TABLE_NAME_ATTRACTIONS: ${self:custom.tableName.attractions}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

resources:
  - ${file(resources/dynamodb-table.yml)}
