Resources:
  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName.table}
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

Outputs:
  ProfileTableArn:
    Value:
      Fn::GetAtt:
        - ProfileTable
        - Arn
    Export:
      Name: ${self:custom.stage}-ExtProfileTableArn
