Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName.users}
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: mobileNumber
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email 
              KeyType: HASH
          Projection:
            ProjectionType: 'ALL'
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: mobile-number-index
          KeySchema:
            - AttributeName: mobileNumber
              KeyType: HASH
          Projection:
            ProjectionType: 'ALL'
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5